spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    jdbc-url: jdbc:mysql://tagdog.io:3306/portal?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: portal
    password: 'portal#1'
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

server:  
  port: ${PORT:8080}

# Mybatis
mybatis:
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true